language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2.101
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true 
  - DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
  - dotnet build ./src/lib/Xutils/Xutils.Extensions/Xutils.Extensions.csproj
  - dotnet build ./src/lib/Xutils/Xutils.Extensions.ASPNETCore/Xutils.Extensions.ASPNETCore.csproj
